export const data = [
  {
    username: 'lucassiqz',
    completeName: 'Lucas Siqueira',
    description: 'Software Engineer',
    place: 'Brasilia-DF',
    birth: '14 de julho de 1997',
    following: [{ username: 'guilherme-aguiar' }, { username: 'thiagoo' }],
  },
  {
    username: 'guilherme-aguiar',
    completeName: 'Guilherme Aguiar',
    description: 'Software Engineer',
    place: 'Brasilia-DF',
    following: [{ username: 'caiooliv' }, { username: 'carlinhos' }],
  },
  {
    username: 'caiooliv',
    completeName: 'Caio Oliveira',
    description: 'Software Engineer',
    place: 'Brasilia-DF',
    birth: '18 de janeiro de 1997',
    following: [
      { username: 'carlinhos' },
      { username: 'guilherme-aguiar' },
      { username: 'alex' },
    ],
  },
  {
    username: 'carlinhos',
    description: 'Software Engineer',
    place: 'Rio de Janeiro-RJ',
    completeName: 'Carlos Eduardo',
    following: [{ username: 'matheus-rn' }],
  },
  {
    username: 'matheus-rn',
    completeName: 'Matheus Rabelo Nonato',
    description: 'Software Engineer',
    place: 'Brasilia-DF',
    following: [{ username: 'carlinhos' }, { username: 'thiagoo' }],
  },
  {
    username: 'thiagoo',
    completeName: 'Thiago Assis',
    description: 'Software Engineer',
    place: 'São Paulo-SP',
    following: [{ username: 'we11' }],
  },
  {
    username: 'we11',
    description: 'Software Engineer',
    place: 'Rio de Janeiro-RJ',
    completeName: 'Wellington Santiago',
    following: [{ username: 'an@_maria' }, { username: 'mario' }],
  },
  {
    username: 'an@_maria',
    description: 'Software Engineer',
    place: 'Curitiba-PR',
    completeName: 'Ana Maria da Silva',
    following: [{ username: 'alex' }, { username: 'mario' }],
  },
  {
    username: 'mario',
    description: 'Software Engineer',
    place: 'Curitiba-PR',
    completeName: 'Mario Ferreira',
    following: [{ username: 'an@_maria' }],
  },
  {
    username: 'alex',
    description: 'Software Engineer',
    place: 'Curitiba-PR',
    completeName: 'Alex Oliveira',
    following: [],
  },
];
